const LISTINGS = [
  {
    "id": 1773877619191,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Rent : RM 3,800/month",
    "rooms": "3",
    "bathrooms": "2",
    "builtup": "950 sqft",
    "furnishing": "Fully Furnished",
    "tenure": "-",
    "description": "Condo For Rent – Residensi Ava @ Kiara Bay, Kepong\n\nProperty Details\n• Type B Layout\n• Built-up: 950 sqft\n• 3 Bedrooms\n• 2 Bathrooms\n• Fully Furnished\n• Extensively Renovated\n• Move-in Condition\n• Available from 10/04\n\nRental Price: RM3,800 / month (Negotiable)\n\nStrategic location in Kiara Bay, Kepong with easy access to:\n• Desa ParkCity\n• Metro Prima\n• MRR2 & DUKE Highway\n• AEON Metro Prima and surrounding amenities\n\nIdeal for families or working professionals.\n\nFor viewing arrangements contact:\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "RA6 (18).jpeg",
      "RA6 (1).jpeg",
      "RA6 (2).jpeg",
      "RA6 (3).jpeg",
      "RA6 (4).jpeg",
      "RA6 (5).jpeg",
      "RA6 (6).jpeg",
      "RA6 (7).jpeg",
      "RA6 (8).jpeg",
      "RA6 (9).jpeg",
      "RA6 (10).jpeg",
      "RA6 (11).jpeg",
      "RA6 (12).jpeg",
      "RA6 (13).jpeg",
      "RA6 (14).jpeg",
      "RA6 (15).jpeg",
      "RA6 (16).jpeg",
      "RA6 (17).jpeg"
    ],
    "privateNotes": "Michelle #A23-03-@Residensi Ava for rent (6) Teo , +60 12-680 4698"
  },
  {
    "id": 1773876991951,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Sale : RM 590,000",
    "rooms": "3",
    "bathrooms": "2",
    "builtup": "947 sqft",
    "furnishing": "Partially Furnished",
    "tenure": "Leasehold",
    "description": "Condo For Sale – Residensi Ava @ Kiara Bay, Kepong\n\nProperty Details:\n• Built-up: 947 sqft\n• 3 Bedrooms\n• 2 Bathrooms\n• Leasehold\n\nHighlights:\n• Perfect KL city skyline view\n• Practical layout suitable for families\n• Located within the developing Kiara Bay township\n• Modern facilities including swimming pool, gymnasium and recreational areas\n• Easy access to Kepong, Desa ParkCity and major highways\n\nSelling Price: RM590,000 (Negotiable)\n\nSuitable for own stay or investment.\n\nFor viewing or more information contact:\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "RA7 (1).jpeg",
      "RA7 (2).jpeg",
      "RA7 (3).jpeg",
      "RA7 (4).jpeg",
      "RA7 (5).jpeg",
      "RA7 (6).jpeg",
      "RA7 (7).jpeg"
    ],
    "privateNotes": "SWLim @residency ava (7) , +60 12-208 1990"
  },
  {
    "id": 1773875829820,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Sale : RM 850,000",
    "rooms": "4",
    "bathrooms": "2",
    "builtup": "1285 sqft",
    "furnishing": "Partially Furnished",
    "tenure": "Leasehold",
    "description": "Apartment For Sale – Residensi Ava @ Kiara Bay, Kepong\n\nSpacious layout unit available at Residensi Ava @ Kiara Bay, a modern lakeside development located near Kepong and Desa ParkCity with excellent connectivity and lifestyle amenities.\n\nProperty Details:\n• Built-up: 1,285 sqft\n• 4 Bedrooms\n• 2 Bathrooms\n• 2 Car Parks\n• Leasehold\n• Strata Title\n• Non-Bumi Lot\n• Vacant Unit\n\nSelling Price: RM850,000\n\nStrategic location with easy access to:\n• Desa ParkCity\n• Metro Prima\n• MRR2 & DUKE Highway\n• AEON Metro Prima\n• Nearby shops and restaurants\n\nSuitable for own stay or investment.\n\nContact for viewing arrangement.\n\nCo-agency welcome.\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "RA3 (1).jpeg",
      "RA3 (2).jpeg",
      "RA3 (3).jpeg",
      "RA3 (4).jpeg",
      "RA3 (5).jpeg"
    ],
    "privateNotes": "Co broke with mummy"
  },
  {
    "id": 1773875638456,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Sale : RM 610,000",
    "rooms": "2",
    "bathrooms": "2",
    "builtup": "813 sqft",
    "furnishing": "Partially Furnished",
    "tenure": "Leasehold",
    "description": "Residensi Ava @ Kiara Bay Apartment – For Sale\n\nBuilt-up: 813 sqft\n\n• 2 Bedrooms\n• 2 Bathrooms\n• 2 Carparks\n• Partially Furnished\n• Facing Pool & Parking View\n\nTenure: Leasehold\nTitle: Strata Title\nLot Type: Bumi Lot\nUnit Status: Tenanted\n\nSelling Price: RM610,000\n\nStrategic location in Kiara Bay near Kepong with convenient access to major highways, retail and lifestyle amenities.\n\nNearby:\n• Kepong\n• Desa ParkCity\n• Metro Prima\n• MRR2 Highway\n• Easy access to KL city\n\nCo-agency welcome.",
    "whatsapp": "60166287357",
    "photos": [
      "RA2(1).jpeg",
      "RA2(2).jpeg",
      "RA2(3).jpeg",
      "RA2(4).jpeg",
      "RA2(5).jpeg",
      "RA2(6).jpeg",
      "RA2(7).jpeg",
      "RA2(8).jpeg",
      "RA2(9).jpeg",
      "RA2(10).jpeg",
      "RA2(11).jpeg",
      "RA2(12).jpeg"
    ],
    "privateNotes": "#A-07-07-@Residensi Ava(2) for sale , +60 11-2549 3614"
  }
];
