const LISTINGS = [
  {
    "id": 1773894737531,
    "type": "listing",
    "title": "Sri Damansara 2 Storey Terrace",
    "location": "Sri Damansara, Kuala Lumpur",
    "price": "For Sale : RM1.5 Mil , For Rent : RM2,800/month",
    "rooms": "3+1",
    "bathrooms": "3",
    "builtup": "1650 sqft",
    "furnishing": "Partly Furnished",
    "tenure": "Freehold",
    "description": "Spacious 2-storey terrace located in a mature Sri Damansara neighbourhood.\n\nProperty Features:\n• Spacious living room  \n• Large dining area & kitchen  \n• 1 study room on ground floor (convertible to bedroom)  \n• 1 bathroom on ground floor  \n\nUpstairs Layout:\n• 3 Bedrooms  \n• Master bedroom with fully tiled ensuite bathroom  \n• 1 shared tiled bathroom  \n• Built-in wardrobes in bedrooms  \n• Small upstairs common space  \n\nFully tiled flooring throughout the house  \n\nLocated in a mature neighbourhood close to amenities, schools, restaurants and conveniences.\n\nSuitable for own stay or rental investment.\n\nCo-agency welcome.",
    "whatsapp": "60166287357",
    "photos": [
      "SD10No1 (1).jpeg",
      "SD10No1 (2).jpeg",
      "SD10No1 (3).jpeg",
      "SD10No1 (4).jpeg",
      "SD10No1 (5).jpeg",
      "SD10No1 (6).jpeg",
      "SD10No1 (7).jpeg",
      "SD10No1 (8).jpeg",
      "SD10No1 (9).jpeg",
      "SD10No1 (10).jpeg",
      "SD10No1 (11).jpeg",
      "SD10No1 (12).jpeg"
    ],
    "privateNotes": "Mummy auntie friend",
    "status": "Available"
  },
  {
    "id": 1773893951166,
    "type": "listing",
    "title": "Emhub @Bukit Raja Commercial unit",
    "location": "Klang, Selangor",
    "price": "Rm 150 - 200 psf",
    "rooms": "-",
    "bathrooms": "-",
    "builtup": "2196 sqft - 5088 sqft",
    "furnishing": "-",
    "tenure": "leasehold",
    "description": "Unique concept unit with dual functionality – suitable for both commercial and office use.\n\nDirect “drive-up” convenience allows easy access right to your unit, ideal for business operations, loading or quick drop-offs.\n\nComes with 2 car park spaces directly in front of the unit, providing rare convenience for both owners and customers.\n\nFlexible layout suitable for office, retail, showroom or small business setup.\n\nSales Gallery Now at Kota Damansara \n\nCurrent selling new built duplicated layout at Bukit Raja, Klang",
    "whatsapp": "60166287357",
    "photos": [
      "EmhubProject (1).jpeg",
      "EmhubProject (2).jpeg",
      "EmhubProject (3).jpeg",
      "EmhubProject (4).jpeg",
      "EmhubProject (5).jpeg",
      "EmhubProject (6).jpeg",
      "EmhubProject (7).jpeg",
      "EmhubProject (8).jpeg",
      "EmhubProject (9).jpeg",
      "EmhubProject (10).jpeg",
      "EmhubProject (11).jpeg",
      "EmhubProject (12).jpeg",
      "EmhubProject (13).jpeg",
      "EmhubProject (14).jpeg",
      "EmhubProject (15).jpeg",
      "EmhubProject (16).jpeg",
      "EmhubProject (17).jpeg",
      "EmhubProject (18).jpeg",
      "EmhubProject (19).jpeg",
      "EmhubProject (20).jpeg",
      "EmhubProject (21).jpeg",
      "EmhubProject (22).jpeg"
    ],
    "privateNotes": "company project Emhub  @ bukit raja",
    "status": "Available"
  },
  {
    "id": 1773892656321,
    "type": "listing",
    "title": "Bandar Sri Damansara - End Lot 2 storey Terrace",
    "location": "Sri Damansara, Kuala Lumpur",
    "price": "For Sale : RM1,200,000 , For Rent : RM2,500/month",
    "rooms": "4",
    "bathrooms": "3",
    "builtup": "1800 sqft",
    "furnishing": "Empty unit",
    "tenure": "Freehold",
    "description": "Prime Sri Damansara location  \nWalking distance to restaurants, groceries & retail  \n\nSelling Price: RM1.2M  \nRental: RM2,500/month  \n\nEnd lot / corner unit with nice open view  \n\nProperty Details:\n• 4 Bedrooms (1 downstairs, 3 upstairs)  \n• 3 Bathrooms  \n• High ceiling living hall with chandelier  \n• Dining area  \n• Closed kitchen with sliding door  \n• Small common space upstairs with ceiling fan  \n\nParking: 2 inside + 1 outside  \n\nChinese owner  \nPreviously tenanted for over 20 years continuously  \n\nCo-agency welcome.",
    "whatsapp": "60166287357",
    "photos": [
      "No2SD8 (1).jpeg",
      "No2SD8 (2).jpeg",
      "No2SD8 (3).jpeg",
      "No2SD8 (4).jpeg",
      "No2SD8 (5).jpeg",
      "No2SD8 (6).jpeg",
      "No2SD8 (7).jpeg",
      "No2SD8 (8).jpeg",
      "No2SD8 (9).jpeg",
      "No2SD8 (10).jpeg",
      "No2SD8 (11).jpeg",
      "No2SD8 (12).jpeg",
      "No2SD8 (13).jpeg",
      "No2SD8 (14).jpeg"
    ],
    "privateNotes": "sd 8 end lot",
    "status": "Available"
  },
  {
    "id": 1773892254532,
    "type": "listing",
    "title": "Bandar Sri Damansara - 2 storey Terrace",
    "location": "Sri Damansara, Kuala Lumpur",
    "price": "For Sale : RM1.2Mil",
    "rooms": "3b+1s",
    "bathrooms": "3",
    "builtup": "1650 sqft",
    "furnishing": "Empty Unit",
    "tenure": "Freehold Strata title",
    "description": "North facing unit  \nLand size: 22 x 75  \n\nProperty Details:\n• 3 Bedrooms + 1 Study  \n• 3 Bathrooms  \n• 1 ground floor room  \n• 1 shared bathroom upstairs  \n• 1 master ensuite  \n\nParking: 2 inside + 1 outside  \n\nGated & guarded community  \nFront yard & backyard  \n\nWalking distance to school, restaurants, clinic & groceries  \n\nCo-agency welcome.",
    "whatsapp": "60166287357",
    "photos": [
      "SD8No1 (1).jpeg",
      "SD8No1 (2).jpeg",
      "SD8No1 (3).jpeg",
      "SD8No1 (4).jpeg",
      "SD8No1 (5).jpeg",
      "SD8No1 (6).jpeg",
      "SD8No1 (7).jpeg",
      "SD8No1 (8).jpeg",
      "SD8No1 (9).jpeg",
      "SD8No1 (10).jpeg",
      "SD8No1 (11).jpeg",
      "SD8No1 (12).jpeg",
      "SD8No1 (13).jpeg",
      "SD8No1 (14).jpeg",
      "SD8No1 (15).jpeg",
      "SD8No1 (16).jpeg",
      "SD8No1 (17).jpeg",
      "SD8No1 (18).jpeg"
    ],
    "privateNotes": "Mummy co broke end lot sd 12 I see myself at wohgei",
    "status": "Available"
  },
  {
    "id": 1773891614530,
    "type": "listing",
    "title": "Sungai Buloh Factory",
    "location": "Sungai Buloh, Selangor",
    "price": "For Rent : RM15,000/month",
    "rooms": "-",
    "bathrooms": "-",
    "builtup": "10,000 sqft",
    "furnishing": "-",
    "tenure": "-",
    "description": "Power supply: 150 amps (TNB)\nTruck & container accessible\n\nRental: RM15,000/month (negotiable)\nAvailable from 1 April 2026\n\nSuitable for warehouse, storage or light industrial use.\n\nStrategic Sungai Buloh location with good accessibility.\n\nCo-agency welcome.",
    "whatsapp": "60166287357",
    "photos": [
      "sungai_buloh1.jpeg"
    ],
    "privateNotes": "Co broke mummy",
    "status": "Available"
  },
  {
    "id": 1773888817373,
    "title": "Westside One @ Desa ParkCity ",
    "location": "Desa ParkCity, Kuala Lumpur",
    "price": "For Rent : RM5,500/month",
    "rooms": "3+1",
    "bathrooms": "3",
    "builtup": "1701 sqft",
    "furnishing": "Fully Furnished",
    "tenure": "Leasehold",
    "description": "Available from 1 April 2026\nCurrently tenanted – viewing can be arranged\n\nLocated in Desa ParkCity, one of KL’s most sought-after lifestyle townships:\n• Beautiful lake park community\n• International school & hospital within the township\n• Strong expatriate community\n• Pet-friendly environment\n• High security & well-managed township\n\nClose to Waterfront & Arkaid – popular dining, retail & lifestyle hubs.\n\nCo-agency welcome",
    "whatsapp": "60166287357",
    "photos": [
      "Desapark1 (1).jpeg",
      "Desapark1 (2).jpeg",
      "Desapark1 (3).jpeg",
      "Desapark1 (4).jpeg",
      "Desapark1 (5).jpeg",
      "Desapark1 (6).jpeg"
    ],
    "privateNotes": "Co broke with mummy ",
    "status": "Available"
  },
  {
    "id": 1773880488466,
    "title": "8trium - Front Facing shoplot",
    "location": "Sri Damansara",
    "price": "For Rent : RM2.90psf",
    "rooms": "-",
    "bathrooms": "-",
    "builtup": "1495 sqft",
    "furnishing": "-",
    "tenure": "-",
    "description": "Commercial Unit For Rent – Atrium Sri Damansara\n\nFront-facing unit with strong visibility and high exposure.\n\nDirect escalator access from the main entrance, suitable for retail, showroom or office use.\n\nRental Price: RM2.90 psf\n\nLocated in an established commercial hub with MRT nearby, loading bay facilities, cargo lift and ample multi-level parking.\n\nHigh exposure unit with strong walk-in potential.\n\nCo-agency welcome.\n\nFor details or viewing arrangement contact:\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "8Trium1lot (1).jpeg",
      "8Trium1lot (2).jpeg",
      "8Trium1lot (3).jpeg",
      "8Trium1lot (4).jpeg",
      "8Trium1lot (5).jpeg",
      "8Trium1lot (6).jpeg",
      "8Trium1lot (7).jpeg",
      "8Trium1lot (8).jpeg",
      "8Trium1lot (9).jpeg",
      "8Trium1lot (10).jpeg",
      "8Trium1lot (11).jpeg"
    ],
    "privateNotes": "Co broke with mummy 8trium developer",
    "status": "Available"
  },
  {
    "id": 1773879543969,
    "title": "8trium - Rear Facing shoplot",
    "location": "Sri Damansara",
    "price": "For Rent : RM2.70psf",
    "rooms": "-",
    "bathrooms": "-",
    "builtup": "1st lot @2047sqft ; 2nd lot @1978sqft",
    "furnishing": "Fully Furnished",
    "tenure": "-",
    "description": "Commercial Unit For Rent – Atrium, Sri Damansara\n\nRear-facing unit with closest access to cargo lift, suitable for office, storage or backend operations.\n\nSizes available:\n• 2,047 sqft\n• 1,978 sqft\n\nSeparate units – can rent individually or together.\n\nRental Price: RM2.70 psf (Negotiable)\n\nLocated within an established commercial hub with loading bay facilities, multi-level parking and MRT nearby.\n\nStrategic location with convenient access around Sri Damansara.\n\nCo-agency welcome.\n\nFor details or viewing arrangement contact:\n\nKenneth Lai\nReal Estate Negotiator\nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "8Trium2lot (1).jpeg",
      "8Trium2lot (2).jpeg",
      "8Trium2lot (3).jpeg",
      "8Trium2lot (4).jpeg",
      "8Trium2lot (5).jpeg",
      "8Trium2lot (6).jpeg",
      "8Trium2lot (7).jpeg",
      "8Trium2lot (8).jpeg",
      "8Trium2lot (9).jpeg",
      "8Trium2lot (10).jpeg",
      "8Trium2lot (11).jpeg",
      "8Trium2lot (12).jpeg",
      "8Trium2lot (13).jpeg",
      "8Trium2lot (14).jpeg",
      "8Trium2lot (15).jpeg",
      "8Trium2lot (16).jpeg",
      "8Trium2lot (17).jpeg",
      "8Trium2lot (18).jpeg",
      "8Trium2lot (19).jpeg",
      "8Trium2lot (20).jpeg",
      "8Trium2lot (21).jpeg",
      "8Trium2lot (22).jpeg"
    ],
    "privateNotes": "Co broke with mummy 8trium developer",
    "status": "Available"
  },
  {
    "id": 1773877619191,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Rent : RM 3,800/month",
    "rooms": "3",
    "bathrooms": "2",
    "builtup": "950 sqft",
    "furnishing": "Fully Furnished",
    "tenure": "-",
    "description": "Condo For Rent – Residensi Ava @ Kiara Bay, Kepong\n\nProperty Details\n• Type B Layout\n• Built-up: 950 sqft\n• 3 Bedrooms\n• 2 Bathrooms\n• Fully Furnished\n• Extensively Renovated\n• Move-in Condition\n• Available from 10/04\n\nRental Price: RM3,800 / month (Negotiable)\n\nStrategic location in Kiara Bay, Kepong with easy access to:\n• Desa ParkCity\n• Metro Prima\n• MRR2 & DUKE Highway\n• AEON Metro Prima and surrounding amenities\n\nIdeal for families or working professionals.\n\nFor viewing arrangements contact:\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "RA6 (18).jpeg",
      "RA6 (1).jpeg",
      "RA6 (2).jpeg",
      "RA6 (3).jpeg",
      "RA6 (4).jpeg",
      "RA6 (5).jpeg",
      "RA6 (6).jpeg",
      "RA6 (7).jpeg",
      "RA6 (8).jpeg",
      "RA6 (9).jpeg",
      "RA6 (10).jpeg",
      "RA6 (11).jpeg",
      "RA6 (12).jpeg",
      "RA6 (13).jpeg",
      "RA6 (14).jpeg",
      "RA6 (15).jpeg",
      "RA6 (16).jpeg",
      "RA6 (17).jpeg"
    ],
    "privateNotes": "Michelle #A23-03-@Residensi Ava for rent (6) Teo , +60 12-680 4698",
    "status": "Available"
  },
  {
    "id": 1773876991951,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Sale : RM 590,000",
    "rooms": "3",
    "bathrooms": "2",
    "builtup": "947 sqft",
    "furnishing": "Partially Furnished",
    "tenure": "Leasehold",
    "description": "Condo For Sale – Residensi Ava @ Kiara Bay, Kepong\n\nProperty Details:\n• Built-up: 947 sqft\n• 3 Bedrooms\n• 2 Bathrooms\n• Leasehold\n\nHighlights:\n• Perfect KL city skyline view\n• Practical layout suitable for families\n• Located within the developing Kiara Bay township\n• Modern facilities including swimming pool, gymnasium and recreational areas\n• Easy access to Kepong, Desa ParkCity and major highways\n\nSelling Price: RM590,000 (Negotiable)\n\nSuitable for own stay or investment.\n\nFor viewing or more information contact:\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "RA7 (1).jpeg",
      "RA7 (2).jpeg",
      "RA7 (3).jpeg",
      "RA7 (4).jpeg",
      "RA7 (5).jpeg",
      "RA7 (6).jpeg",
      "RA7 (7).jpeg"
    ],
    "privateNotes": "SWLim @residency ava (7) , +60 12-208 1990"
  },
  {
    "id": 1773875829820,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Sale : RM 850,000",
    "rooms": "4",
    "bathrooms": "2",
    "builtup": "1285 sqft",
    "furnishing": "Partially Furnished",
    "tenure": "Leasehold",
    "description": "Apartment For Sale – Residensi Ava @ Kiara Bay, Kepong\n\nSpacious layout unit available at Residensi Ava @ Kiara Bay, a modern lakeside development located near Kepong and Desa ParkCity with excellent connectivity and lifestyle amenities.\n\nProperty Details:\n• Built-up: 1,285 sqft\n• 4 Bedrooms\n• 2 Bathrooms\n• 2 Car Parks\n• Leasehold\n• Strata Title\n• Non-Bumi Lot\n• Vacant Unit\n\nSelling Price: RM850,000\n\nStrategic location with easy access to:\n• Desa ParkCity\n• Metro Prima\n• MRR2 & DUKE Highway\n• AEON Metro Prima\n• Nearby shops and restaurants\n\nSuitable for own stay or investment.\n\nContact for viewing arrangement.\n\nCo-agency welcome.\n\nKenneth Lai  \nReal Estate Negotiator  \nOne Maker Realty Group",
    "whatsapp": "60166287357",
    "photos": [
      "RA3 (1).jpeg",
      "RA3 (2).jpeg",
      "RA3 (3).jpeg",
      "RA3 (4).jpeg",
      "RA3 (5).jpeg"
    ],
    "privateNotes": "Co broke with mummy"
  },
  {
    "id": 1773875638456,
    "title": "Residensi Ava @ Kiara Bay",
    "location": "Kiara Bay / Kepong",
    "price": "For Sale : RM 610,000",
    "rooms": "2",
    "bathrooms": "2",
    "builtup": "813 sqft",
    "furnishing": "Partially Furnished",
    "tenure": "Leasehold",
    "description": "Residensi Ava @ Kiara Bay Apartment – For Sale\n\nBuilt-up: 813 sqft\n\n• 2 Bedrooms\n• 2 Bathrooms\n• 2 Carparks\n• Partially Furnished\n• Facing Pool & Parking View\n\nTenure: Leasehold\nTitle: Strata Title\nLot Type: Bumi Lot\nUnit Status: Tenanted\n\nSelling Price: RM610,000\n\nStrategic location in Kiara Bay near Kepong with convenient access to major highways, retail and lifestyle amenities.\n\nNearby:\n• Kepong\n• Desa ParkCity\n• Metro Prima\n• MRR2 Highway\n• Easy access to KL city\n\nCo-agency welcome.",
    "whatsapp": "60166287357",
    "photos": [
      "RA2(1).jpeg",
      "RA2(2).jpeg",
      "RA2(3).jpeg",
      "RA2(4).jpeg",
      "RA2(5).jpeg",
      "RA2(6).jpeg",
      "RA2(7).jpeg",
      "RA2(8).jpeg",
      "RA2(9).jpeg",
      "RA2(10).jpeg",
      "RA2(11).jpeg",
      "RA2(12).jpeg"
    ],
    "privateNotes": "#A-07-07-@Residensi Ava(2) for sale , +60 11-2549 3614"
  }
];
